//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4971.
// 
namespace LoginToDevice.WebReference_new {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://192.168.137.1/2012_10_04/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/conString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string conString() {
            object[] results = this.Invoke("conString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconString(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("conString", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndconString(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OpenConnection() {
            object[] results = this.Invoke("OpenConnection", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOpenConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OpenConnection", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndOpenConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloseConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CloseConnection() {
            object[] results = this.Invoke("CloseConnection", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCloseConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CloseConnection", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCloseConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Modify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Modify(string query) {
            this.Invoke("Modify", new object[] {
                        query});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginModify(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Modify", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndModify(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Search(string query, int num_of_columns, int num_of_rows) {
            object[] results = this.Invoke("Search", new object[] {
                        query,
                        num_of_columns,
                        num_of_rows});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearch(string query, int num_of_columns, int num_of_rows, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Search", new object[] {
                        query,
                        num_of_columns,
                        num_of_rows}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string emp_ID) {
            object[] results = this.Invoke("login", new object[] {
                        emp_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string emp_ID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        emp_ID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_visit_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_visit_id(string chassisNo) {
            object[] results = this.Invoke("get_visit_id", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_visit_id(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_visit_id", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_visit_id(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_feature_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_feature_id(string chassisNo) {
            object[] results = this.Invoke("get_feature_id", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_feature_id(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_feature_id", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_feature_id(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_feature_name", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_feature_name(string feature_id) {
            object[] results = this.Invoke("get_feature_name", new object[] {
                        feature_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_feature_name(string feature_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_feature_name", new object[] {
                        feature_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_feature_name(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_special_notes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_special_notes(string chassisNo) {
            object[] results = this.Invoke("get_special_notes", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_special_notes(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_special_notes", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_special_notes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/release_vehi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string release_vehi(string chassisNo) {
            object[] results = this.Invoke("release_vehi", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginrelease_vehi(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("release_vehi", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endrelease_vehi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/check_payment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string check_payment(string chassisNo) {
            object[] results = this.Invoke("check_payment", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincheck_payment(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("check_payment", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endcheck_payment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_slot_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_slot_id(string chassisNo) {
            object[] results = this.Invoke("get_slot_id", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_slot_id(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_slot_id", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_slot_id(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_slot_empty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_slot_empty(string slot_id) {
            this.Invoke("update_slot_empty", new object[] {
                        slot_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_slot_empty(string slot_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_slot_empty", new object[] {
                        slot_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_slot_empty(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_vehi_data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_vehi_data(string chassisNo) {
            object[] results = this.Invoke("get_vehi_data", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_vehi_data(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_vehi_data", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endget_vehi_data(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_driver_assign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_driver_assign(string time, string chassisNo, string empID) {
            this.Invoke("update_driver_assign", new object[] {
                        time,
                        chassisNo,
                        empID});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_driver_assign(string time, string chassisNo, string empID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_driver_assign", new object[] {
                        time,
                        chassisNo,
                        empID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_driver_assign(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_vehi_feature", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insert_vehi_feature(string chassisNo, string feature) {
            this.Invoke("insert_vehi_feature", new object[] {
                        chassisNo,
                        feature});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begininsert_vehi_feature(string chassisNo, string feature, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insert_vehi_feature", new object[] {
                        chassisNo,
                        feature}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endinsert_vehi_feature(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/set_special_notes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void set_special_notes(string chassisNo, string special_notes) {
            this.Invoke("set_special_notes", new object[] {
                        chassisNo,
                        special_notes});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginset_special_notes(string chassisNo, string special_notes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("set_special_notes", new object[] {
                        chassisNo,
                        special_notes}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endset_special_notes(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_vehi_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_vehi_status(string chassisNo, string state) {
            this.Invoke("update_vehi_status", new object[] {
                        chassisNo,
                        state});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_vehi_status(string chassisNo, string state, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_vehi_status", new object[] {
                        chassisNo,
                        state}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_vehi_status(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_tally_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_tally_id(string chassisNo, string tally_id) {
            this.Invoke("update_tally_id", new object[] {
                        chassisNo,
                        tally_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_tally_id(string chassisNo, string tally_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_tally_id", new object[] {
                        chassisNo,
                        tally_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_tally_id(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/storeImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void storeImage(string query, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imgArr) {
            this.Invoke("storeImage", new object[] {
                        query,
                        imgArr});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstoreImage(string query, byte[] imgArr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("storeImage", new object[] {
                        query,
                        imgArr}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndstoreImage(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrieve_image", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] retrieve_image(string query) {
            object[] results = this.Invoke("retrieve_image", new object[] {
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginretrieve_image(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieve_image", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] Endretrieve_image(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_profile_pic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] get_profile_pic(string emp_id) {
            object[] results = this.Invoke("get_profile_pic", new object[] {
                        emp_id});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_profile_pic(string emp_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_profile_pic", new object[] {
                        emp_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] Endget_profile_pic(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/security_accept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void security_accept(string chassis_no, string security_id, string date_time) {
            this.Invoke("security_accept", new object[] {
                        chassis_no,
                        security_id,
                        date_time});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsecurity_accept(string chassis_no, string security_id, string date_time, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("security_accept", new object[] {
                        chassis_no,
                        security_id,
                        date_time}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endsecurity_accept(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_inquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void add_inquiry(string chassis_no, string date_time, string description) {
            this.Invoke("add_inquiry", new object[] {
                        chassis_no,
                        date_time,
                        description});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginadd_inquiry(string chassis_no, string date_time, string description, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("add_inquiry", new object[] {
                        chassis_no,
                        date_time,
                        description}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endadd_inquiry(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_inquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_inquiry(string chassis_no, string date_time, string description) {
            this.Invoke("update_inquiry", new object[] {
                        chassis_no,
                        date_time,
                        description});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_inquiry(string chassis_no, string date_time, string description, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_inquiry", new object[] {
                        chassis_no,
                        date_time,
                        description}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_inquiry(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/security_release", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void security_release(string chassis_no, string security_id, string date_time, string wharf_id) {
            this.Invoke("security_release", new object[] {
                        chassis_no,
                        security_id,
                        date_time,
                        wharf_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsecurity_release(string chassis_no, string security_id, string date_time, string wharf_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("security_release", new object[] {
                        chassis_no,
                        security_id,
                        date_time,
                        wharf_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endsecurity_release(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delete_vehi_key_and_insert_to_oldVehi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete_vehi_key_and_insert_to_oldVehi(string chassisNo) {
            this.Invoke("delete_vehi_key_and_insert_to_oldVehi", new object[] {
                        chassisNo});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindelete_vehi_key_and_insert_to_oldVehi(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("delete_vehi_key_and_insert_to_oldVehi", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Enddelete_vehi_key_and_insert_to_oldVehi(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/tally_accept_transship", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void tally_accept_transship(string chassis_no, string tally_id, string date_time) {
            this.Invoke("tally_accept_transship", new object[] {
                        chassis_no,
                        tally_id,
                        date_time});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begintally_accept_transship(string chassis_no, string tally_id, string date_time, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("tally_accept_transship", new object[] {
                        chassis_no,
                        tally_id,
                        date_time}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endtally_accept_transship(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_sms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void send_sms(string sms_id, string message) {
            this.Invoke("send_sms", new object[] {
                        sms_id,
                        message});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsend_sms(string sms_id, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("send_sms", new object[] {
                        sms_id,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endsend_sms(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/driver_assign_for_vehi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void driver_assign_for_vehi(string driver_id, string chassi_no) {
            this.Invoke("driver_assign_for_vehi", new object[] {
                        driver_id,
                        chassi_no});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindriver_assign_for_vehi(string driver_id, string chassi_no, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("driver_assign_for_vehi", new object[] {
                        driver_id,
                        chassi_no}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Enddriver_assign_for_vehi(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_slot_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_slot_status(string state, string slot_id) {
            this.Invoke("update_slot_status", new object[] {
                        state,
                        slot_id});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginupdate_slot_status(string state, string slot_id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("update_slot_status", new object[] {
                        state,
                        slot_id}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endupdate_slot_status(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/count_rows", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int count_rows(string query) {
            object[] results = this.Invoke("count_rows", new object[] {
                        query});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincount_rows(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("count_rows", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endcount_rows(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkVehicleState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkVehicleState(string chassisNo) {
            object[] results = this.Invoke("checkVehicleState", new object[] {
                        chassisNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckVehicleState(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkVehicleState", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckVehicleState(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isTallyCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isTallyCheck(string chassi) {
            object[] results = this.Invoke("isTallyCheck", new object[] {
                        chassi});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisTallyCheck(string chassi, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isTallyCheck", new object[] {
                        chassi}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndisTallyCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkDriverAssignIsOk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkDriverAssignIsOk(string chassisFromTextBox) {
            object[] results = this.Invoke("checkDriverAssignIsOk", new object[] {
                        chassisFromTextBox});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckDriverAssignIsOk(string chassisFromTextBox, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkDriverAssignIsOk", new object[] {
                        chassisFromTextBox}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcheckDriverAssignIsOk(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkSecurityIsOk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool checkSecurityIsOk(string chassisNo) {
            object[] results = this.Invoke("checkSecurityIsOk", new object[] {
                        chassisNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincheckSecurityIsOk(string chassisNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkSecurityIsOk", new object[] {
                        chassisNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndcheckSecurityIsOk(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValiedSlotBarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool isValiedSlotBarcode(string slotBarcode) {
            object[] results = this.Invoke("isValiedSlotBarcode", new object[] {
                        slotBarcode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisValiedSlotBarcode(string slotBarcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isValiedSlotBarcode", new object[] {
                        slotBarcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndisValiedSlotBarcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPhone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPhone(string empID) {
            object[] results = this.Invoke("getPhone", new object[] {
                        empID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPhone(string empID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPhone", new object[] {
                        empID}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPhone(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNaviLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNaviLocation(int index) {
            object[] results = this.Invoke("getNaviLocation", new object[] {
                        index});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetNaviLocation(int index, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getNaviLocation", new object[] {
                        index}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetNaviLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Count_vehicles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Count_vehicles() {
            object[] results = this.Invoke("Count_vehicles", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCount_vehicles(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Count_vehicles", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCount_vehicles(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/acceptKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string acceptKey(string bc, string day) {
            object[] results = this.Invoke("acceptKey", new object[] {
                        bc,
                        day});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginacceptKey(string bc, string day, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("acceptKey", new object[] {
                        bc,
                        day}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndacceptKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/releaseKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable releaseKey(string bc) {
            object[] results = this.Invoke("releaseKey", new object[] {
                        bc});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginreleaseKey(string bc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("releaseKey", new object[] {
                        bc}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndreleaseKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vehicle_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable vehicle_details() {
            object[] results = this.Invoke("vehicle_details", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginvehicle_details(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("vehicle_details", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endvehicle_details(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nontranship_vehicle_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable nontranship_vehicle_details() {
            object[] results = this.Invoke("nontranship_vehicle_details", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginnontranship_vehicle_details(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nontranship_vehicle_details", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endnontranship_vehicle_details(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inquiry_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable inquiry_details(string chas) {
            object[] results = this.Invoke("inquiry_details", new object[] {
                        chas});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begininquiry_details(string chas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("inquiry_details", new object[] {
                        chas}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endinquiry_details(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable getData(string emp_id_nic) {
            object[] results = this.Invoke("getData", new object[] {
                        emp_id_nic});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetData(string emp_id_nic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getData", new object[] {
                        emp_id_nic}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndgetData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_employee_login_data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_employee_login_data(string emp_id, string pass) {
            object[] results = this.Invoke("get_employee_login_data", new object[] {
                        emp_id,
                        pass});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_employee_login_data(string emp_id, string pass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_employee_login_data", new object[] {
                        emp_id,
                        pass}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endget_employee_login_data(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/release", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string release(string bc, string time_rel, string Rid, string RName) {
            object[] results = this.Invoke("release", new object[] {
                        bc,
                        time_rel,
                        Rid,
                        RName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginrelease(string bc, string time_rel, string Rid, string RName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("release", new object[] {
                        bc,
                        time_rel,
                        Rid,
                        RName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endrelease(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/portchrgs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string portchrgs(string chas) {
            object[] results = this.Invoke("portchrgs", new object[] {
                        chas});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginportchrgs(string chas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("portchrgs", new object[] {
                        chas}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endportchrgs(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrieve_vehicle_images", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable retrieve_vehicle_images(string chass) {
            object[] results = this.Invoke("retrieve_vehicle_images", new object[] {
                        chass});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginretrieve_vehicle_images(string chass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieve_vehicle_images", new object[] {
                        chass}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endretrieve_vehicle_images(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrieve_vehi_image", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] retrieve_vehi_image(string chas) {
            object[] results = this.Invoke("retrieve_vehi_image", new object[] {
                        chas});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginretrieve_vehi_image(string chas, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("retrieve_vehi_image", new object[] {
                        chas}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] Endretrieve_vehi_image(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/remove_employee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void remove_employee(string emp_id_nic) {
            this.Invoke("remove_employee", new object[] {
                        emp_id_nic});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginremove_employee(string emp_id_nic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("remove_employee", new object[] {
                        emp_id_nic}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endremove_employee(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pay_charges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void pay_charges(string chas, string emp_id, string bank, string total, string wharf, string day) {
            this.Invoke("pay_charges", new object[] {
                        chas,
                        emp_id,
                        bank,
                        total,
                        wharf,
                        day});
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginpay_charges(string chas, string emp_id, string bank, string total, string wharf, string day, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("pay_charges", new object[] {
                        chas,
                        emp_id,
                        bank,
                        total,
                        wharf,
                        day}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endpay_charges(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
}
